### ISSUE TITLE
scan2drive.zekjur.net https listener is currently hardcoded in the source

### ISSUE THREAD

**Issue by dnwe** [stapelberg/scan2drive#20]
👋🏻 thanks for scan2drive!

---

A minor issue and easy to comment out / remove, but would be good if this was cmdline/config driven rather than being hardcoded:

https://github.com/stapelberg/scan2drive/blob/7b30eb9a76617c55c7a6f57867030c73f8f65b95/cmd/scan2drive/scan2drive.go#L390-L394

**Comment by stapelberg** [comment]
Thanks, now fixed!

Let me know if you end up running a scan2drive instance, too, or if you run into any issues :)
