### ISSUE TITLE
scan2drive doesn't append DNSSD Domain to scanner service for Avahi-style name resolution

### ISSUE THREAD

**Issue by dnwe** [stapelberg/scan2drive#21]
Currently scan2drive just tries to access the scanner directly from the hostname found in its DNSSD service description:

https://github.com/stapelberg/scan2drive/blob/8e6da9c5ebe4481e8500ef32b9bcdbc0074eb446/internal/source/airscan/airscan.go#L206-L210

Whereas the original airscan also takes the Domain from the DNSSD response and attempts to connect to it by that:
https://github.com/stapelberg/airscan/blob/9b9f6be23a95c8c8f33e69a3aabeb45e62f7425d/airscan.go#L334-L340

**Comment by stapelberg** [comment]
Should be fixed now! Let me know if that does the trick
