### ISSUE TITLE
Listen address/oauth redirect trouble

### ISSUE THREAD

**Issue by markdrayton** [stapelberg/scan2drive#23]
I'm having some trouble with listen addresses and oauth redirect URLs. I'm sure I am missing something obvious.

From https://github.com/stapelberg/scan2drive/blob/main/README.md:

> You should be able to access the gokrazy web interface at the URL which the gok tool printed. To access the scan2drive web interface, switch to port 7120.

By default scan2drive listens on `localhost` which is (obviously) not reachable over the network. I noticed there were some recent changes around this code (e.g. a33d0c6d3d398fde162f0de25fd4ca03e4c3855a) but from a quick glance it doesn't seem anything has changed much, so I don't understand how it'd have ever been possible to hit port 7120 from another host. Is there something fundamental that I'm misunderstanding about how this part works?

I then tried `-http_listen_address=gokrazy.lan:7120` (my gokrazy's instance hostname), which allowed me to reach the UI, but Google then gave me this error when I tried to sign in:

    device_id and device_name are required for private IP: http://192.168.x.y:7120/oauth

It feels like I'll need to somehow provide an internet-reachable address to which Google can redirect me once authenticated, unless I'm completely lost.

Any clues?

**Comment by markdrayton** [comment]
(Forgot to add: gokrazy etc is a real delight to use. Thanks!)

**Comment by stapelberg** [comment]
Hey @markdrayton 👋

You’re right, this is not a particularly well documented part, and certainly there is a lot of environment-specific complexity regarding HTTP(S) setup.

Essentially, for Google OAuth, you have two options:

1. Run on localhost. This is handy for development and setting up your OAuth on the Google side.
2. Run over the network. This requires having a domain name with a valid TLS certificate (as Google OAuth permits only HTTPS nowadays). scan2drive has builtin support for Let’s Encrypt, but you do need to make your instance reachable over the internet for this to work. An easy way is if you have IPv6 (that’s what I use), or if you set up a port forwarding. You could also supply your own certificate, or run a reverse proxy that terminates TLS. 

Hope this gives you a pointer, but feel free to ask more specific questions if you have any :)

**Comment by markdrayton** [comment]
Okay, short of me Totally Not Getting It this was what I thought the outcome might be. I'll wrestle with IPv6, then. Thanks!
