### ISSUE TITLE
Unable to read client secret file: open /perm/client_secret_...

### ISSUE THREAD

**Issue by YaguraStation** [stapelberg/scan2drive#9]
gokrazy loops on starting `scan2drive`, which remains _restarting_.
from stderr: 
```
  2017/05/04 09:02:43 gokrazy: attempt 357, starting [/user/scan2dri]
  2017/05/04 09:02:43 Unable to read client secret file: open /perm/client_secret_197950901230-jee3asvone1tnh7k2qsshm369723vkun.apps.googleusercontent.com.json: no such file or directory
  2017/05/04 09:02:44 gokrazy: exit status 1
```
Please tell me if I can gather more info about this issue (file system permissions, install breakglass etc). 

**Edit**: /perm is empty.

**Comment by stapelberg** [comment]
I realize this is not well-documented yet, sorry about that. There’s a few rough edges yet, as you can see :).

Please follow https://developers.google.com/drive/v3/web/quickstart/go#step_1_turn_on_the_api_name to obtain a client_secret file, then place it on /perm (from a different computer) and rename it accordingly.

Afterwards, you’ll probably run into issue #4. I can provide an example JSON file when I’m back at home later today.

**Comment by YaguraStation** [comment]
Ah, OK. I see your client ID is hardcoded into [scan2drive.service](https://github.com/stapelberg/scan2drive/blob/2e07c6ce92b1ad965c6af4359384e670d2049bfd/scan2drive.service), [scan2drive.js](https://github.com/stapelberg/scan2drive/blob/df09d67e06dd7a1adc0f7e2af3da39146e381f1a/assets/scan2drive.js), and [main.go](https://github.com/stapelberg/scan2drive/blob/13cfa5729a46c80a61474e40f7ae9043ab3dd98f/main.go) ... which in turn leads to _400 Error: redirect_uri_mismatch_ when trying to sign in. 

But please chill, I am just excitedly following gokrazy. Like many Linux users, I have an ix500 accompanied by some scripts which are working so-so.

**Comment by stapelberg** [comment]
Thanks for pointing this out. I’ll follow up with a fix soon.

Note that scan2drive.service is obsolete, except if you want to offload computation onto a different machine and hence run scan2drive under systemd. I hope I can make computation fast enough on the Raspberry Pi itself (see issue #7) to make that no longer necessary :).

**Comment by stapelberg** [comment]
Before I forget it, here’s the drive_folder.json file:
```
{"Id":"<id>","IconUrl":"https://ssl.gstatic.com/docs/doclist/images/icon_11_collection_list_1.png","Url":"https://docs.google.com/folderview?id=<id>\u0026usp=drive_web","Name":"scan"}
```
where both occurrences of `<id>` are replaced with the last path component when viewing a Google Drive folder in your browser (e.g. `https://drive.google.com/drive/u/0/folders/<id>`).

Removing the hard-coded IDs is still on my radar, but optimizing the scan post-processing was more interesting for the moment :). I have some changes in mind which should yield some more drastic speed-ups.

**Comment by stapelberg** [comment]
I have a change in the works which will make scan2drive enter a setup mode when the client secret is missing. It’ll then serve an HTML page with instructions, guiding you through the process.

**Comment by stapelberg** [comment]
Change done and pushed. Note that the client ID is still hard-coded in scan2drive.js. I’ll work on that next. The settings panel issue (issue #4) still stands, too.

**Comment by stapelberg** [comment]
Okay, both addressed. Give it another shot, and let me know how it goes. Note that you’ll need to use a different hostname than localhost in order for the directory picker to show (see also https://stackoverflow.com/questions/34516182/google-drive-picker-error)

**Comment by YaguraStation** [comment]
Nice easy understandable wizard. Using http://gokrazy.lan:7120. 

But after entering new OAuth client credentials, I firstly get a 404. Then, after refreshing:  _Error idpiframe_initialization_failed: Failed to read the 'localStorage' property from 'Window': Access is denied for this document._ 
![2017-05-18-201845_956x189_scrot](https://cloud.githubusercontent.com/assets/23151113/26217321/384dfbd4-3c07-11e7-9954-7ea84b3c58d0.png)

**Comment by stapelberg** [comment]
Did you list http://gokrazy.lan:7120 in the oauth client secret? It’s possible that needs a few minutes to propagate. Let me know if it still doesn’t work in 15 minutes or so.

**Comment by YaguraStation** [comment]
Yeah had localhost and hostname plus ports specified in the client. Again, great wizard screen of yours! 

Funny enough: So you get the screenshot from above and then click on the whitespace next to _Sign in_ and the Google Drive authorisation pops up in a new window. After clicking _Allow_ one reverts to above mentioned screenshot again. BTW, in earlier builds the _Sign in_ button was Google-branded. 

If I can help out in a more sophisticated way (traces, API Manager log etc), or even trivial stuff (README.md etc) please let me know. Otherwise all of this is not mission critical and I am just happy to learn by experimenting.

**Comment by YaguraStation** [comment]
Just one more finding: _Error idpiframe_initialization_failed_ was caused by me not allowing third-party cookies in the browser. But even without that message, the same behaviour described above can be reproduced. After allowing access, one returns to scan2drive not logged in. 

Then I see that a bunch requests for .js and .css returned with 404s. But I will rather keep still for instructions on how to provide meaningful feedback, if needed. :-)

**Comment by stapelberg** [comment]
Can you reproduce this issue with a fresh browser profile, ideally chrome?

Can you provide a screenshot of the network tab in the developer tools, so that I can see which requests are failing?

**Comment by YaguraStation** [comment]
No problem! 
1. Visiting freshly packed app
2. After entering client creds
3. After sign in and allowance on separate Google Drive API permissions screen
4. After another sign in attempt just for good measure

BTW, account has 2FA switched on. 
![2017-05-19-153234_1914x726_scrot](https://cloud.githubusercontent.com/assets/23151113/26250002/e1c0f936-3ca8-11e7-9c6f-4316e8ea50e1.png)
![2017-05-19-153410_1912x831_scrot](https://cloud.githubusercontent.com/assets/23151113/26250001/e1ad458a-3ca8-11e7-89a4-73134b1af556.png)
![2017-05-19-153501_1911x890_scrot](https://cloud.githubusercontent.com/assets/23151113/26249999/e1a8a070-3ca8-11e7-8cce-cb9b6df27b64.png)
![2017-05-19-153524_1915x909_scrot](https://cloud.githubusercontent.com/assets/23151113/26250000/e1aaa5f0-3ca8-11e7-90c4-79798e77df5a.png)

**Comment by stapelberg** [comment]
Thanks for the additional details. The failing “oauth” requests contain the server-side error message. I just pushed a commit to expose this error message on the page, along with the common fix to revoke permission at https://security.google.com/settings/u/0/security/permissions before retrying.

If that doesn’t help, can you also post a screenshot of the sign-in dialog you get, along with the contents of the failing “oauth” request?

**Comment by stapelberg** [comment]
Also, I can reproduce the issue that the sign in button is not branded. This looks like an issue with Polymer’s vulcanization. The drive picker also doesn’t seem to work correctly. I’ll see if upgrading to Polymer 2.0 is feasible at all, and if that fixes our issues.

**Comment by stapelberg** [comment]
Correction: the drive picker works once you login within the picker, then reload the page and open it again. Annoying, but at least there’s a workaround.

I’m currently experimenting with abandoning Polymer in favor of materializecss, which is drastically simpler. Will keep you posted.

**Comment by YaguraStation** [comment]
Awesome. Will get some testing done tomorrow. Cheers!

**Comment by stapelberg** [comment]
Changes pushed. I’ll file a few bugs for known issues in a second, but what should work is this:

1. follow the wizard to set up client id/client secret
2. log in using your google account
3. click settings, click “folder”
4. if the picker asks you to log in, log in, then reload the page and go to step 3
5. select the destination drive folder
6. scan using the scanner’s hardware scan button
7. once your scan has been processed, it’ll appear in the web interface (and google drive, of course)

**Comment by YaguraStation** [comment]
Not sure what is going on, but I guess it's all related to the folder picker. 
* UI right-hand corner says _not logged in_, button says _Signed in with Google_, tho. Can successfully pick folder from my Drive. 
* Button-scans end with `2017/05/21 19:42:41 scans = map[2017-05-21T19:28:45+02:00:{Sub:106936676900059375926 Scanned:true Converted:true UploadedOriginals:false UploadedPDF:false Renamed:false NewName:} 2017-05-21T19:42:09+02:00:{Sub:106936676900059375926 Scanned:true Converted:true UploadedOriginals:false UploadedPDF:false Renamed:false NewName:}]` for example, but nothing in UI and nothing in Drive. 
* In tests where presumably the picker did not work, documents show up in UI as queued for upload and conversion. But also not in Drive.

**Comment by stapelberg** [comment]
I think the issues you’re facing are all related — for some reason, you’re not properly logged in. Did you try revoking permission and logging in again? Also, what do you see in the developer tools console? Any error messages?

**Comment by YaguraStation** [comment]
Yeah, revoked Drive API permissions and deleted gokrazy.lan cookies with every test. But I will try to find time to review the whole project this week (and potentially new commits), then get back with informed feedback... and away from the end user support mode 😋
